name: Publish Devcontainer Image

on:
  push:
    branches: 
      - main
    tags:
      - 'v*'
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/publish-container.yml'

# Grants permissions to the GITHUB_TOKEN to be able to publish to GitHub Container Registry
permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate image metadata (name, tags, labels) based on the contents of the repository
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: | 
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # Export cache allows Docker to reuse unchanged layers from previous builds
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # context: .devcontainer # Not needed since no data is copied from context to image
          file: .devcontainer/Dockerfile
          push: true  # Evaluate if should push the image or not after build 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
